name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout  ️
        uses: actions/checkout@v3
      - name: Install
        run: |
          npm i
      - name: Package vitepress-plugin-fetch-docs Build
        run: |
          cd packages/@vitepress-custom/vitepress-plugin-fetch-docs
          npm run build
      - name: Package vitepress-plugin-nav Build
        run: |
          cd packages/@vitepress-custom/vitepress-plugin-nav
          npm run build
      - name: Package vitepress-plugin-sidebar Build
        run: |
          cd packages/@vitepress-custom/vitepress-plugin-sidebar
          npm run build
      - name: Docs Build   
        run: |
          npm run build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        # 环境变量
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 vitepress 的默认输出目录
          build_dir: example/.vitepress/dist